<details class='biskoto-search'>
  <summary>
    array(35)
  </summary>

  <dl>
    <dt>["vid"]</dt>
    <dd>string(4) "4381"</dd>

    <dt>["uid"]</dt>
    <dd>string(2) "25"</dd>

    <dt>["title"]</dt>
    <dd>string(45) "Lorem Ipsum"</dd>

    <dt>["body"]</dt>
    <dd>
      <details>
        <summary>
          array(1)
        </summary>
        <dl>
          <dt>
            ["und"]=>
          </dt>
          <dd>
            <details>
              <summary>
                array(1)
              </summary>
              <dl>
                <dt>
                  [0]
                </dt>
                <dd>
                  <details>
                    <summary>
                      array(5)
                    </summary>
                    <dl>
                      <dt>
                        ["value"]
                      </dt>
                      <dd>
                        string(961) "
                        Long Multiline string

                        Lorem Ipsum 
                      "</dd>
                      <dt>
                        ["summary"]
                      </dt>
                      <dd>
                        string(0) ""
                      </dd>
                    </dl>
                  </details>
                </dd>
              </dl>
            </details>
          </dd>
        </dl>
      </details>
    </dd>

    <dt>
      ["field_images"]
    </dt>
    <dd>
      array(0)
    </dd>
    <dt>
      ["cid"]
    </dt>
    <dd>
      string(1) "0"
    </dd>
  </dl>
</details>